### ISSUE TITLE
AmazonLinuxでElasticSearchをインストールしようとしたらハマったよ

### ISSUE THREAD

**Issue by micci184** [MofuMofu2/TB2-ELKStack#3]
> そもそも想定している環境が違うけど、備忘メモとして記載。
> 今後のバージョンアップに役立つかな？w

以下にインストールメモを記載。

## ElasticSearchダウンロード

```bash
# mkdir /opt/elk_stack
# cd /opt/elk_stack
# wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.zip
--2017-03-15 05:33:26--  https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.zip
Resolving artifacts.elastic.co (artifacts.elastic.co)... 107.21.249.70, 107.22.208.105, 54.243.211.74, ...
Connecting to artifacts.elastic.co (artifacts.elastic.co)|107.21.249.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33824223 (32M) [application/zip]
Saving to: ‘elasticsearch-5.2.2.zip’

elasticsearch-5.2.2.zip                                    100%[========================================================================================================================================>]  32.26M  9.31MB/s    in 3.5s

2017-03-15 05:33:30 (9.31 MB/s) - ‘elasticsearch-5.2.2.zip’ saved [33824223/33824223]
# ll
total 33032
-rw-r--r-- 1 root root 33824223 Feb 28 23:22 elasticsearch-5.2.2.zip
# unzip elasticsearch-5.2.2.zip
# ll
total 33036
drwxr-xr-x 7 root root     4096 Feb 24 17:29 elasticsearch-5.2.2
-rw-r--r-- 1 root root 33824223 Feb 28 23:22 elasticsearch-5.2.2.zip
# cd elasticsearch-5.2.2
# cd bin/

### ElasticSearch起動
が、しかし。。メモリが足りないと怒られる。。Orz
# ./elasticsearch
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000000077ad30000, 2060255232, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 2060255232 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/jvm-2644/hs_error.log

```

## インスタンスタイプをアップして再度実行！

* 変更前：t2.small(Mem:2GiB)
* 変更後：t2.medium(Mem:4GiB)

```bash

### Java8使えよ！って怒られる。。Orz
# ./elasticsearch
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
### バージョンが低い
### AmazonLinuxは、Java7がデフォだよね。。
# java -version
java version "1.7.0_131"
OpenJDK Runtime Environment (amzn-2.6.9.0.71.amzn1-x86_64 u131-b00)
OpenJDK 64-Bit Server VM (build 24.131-b00, mixed mode)
```

## Java8をインストール

```bash
# yum -y install java-1.8.0-openjdk-devel

### ぐはっ！まだ低いΣ(･口･)
# java -version
java version "1.7.0_131"
OpenJDK Runtime Environment (amzn-2.6.9.0.71.amzn1-x86_64 u131-b00)
OpenJDK 64-Bit Server VM (build 24.131-b00, mixed mode)

###alternativesコマンドでJavaのバージョンが必要
# alternatives --config java

There are 2 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java
   2           /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java

Enter to keep the current selection[+], or type selection number: 2

### 再度バージョンを確認します。
# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

## 仕切り直して再度実行！！

```bash

### 今度は、rootで実行すんなよ！って怒られました。。わろりんｗ
# bin/elasticsearch
[2017-03-15T06:19:43,841][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.2.jar:5.2.2]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:203) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
        ... 6 more

### てことで、権限をec2-userに変更しまするー
# chown -R ec2-user:ec2-user elasticsearch-5.2.2/
```

## もはや何度目かわからないけど実行！

```bash
$ cd bin/

### 動いた！！
$ ./elasticsearch
[2017-03-15T06:23:07,335][INFO ][o.e.n.Node               ] [] initializing ...
[2017-03-15T06:23:07,413][INFO ][o.e.e.NodeEnvironment    ] [BrYURuf] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [8.2gb], net total_space [9.7gb], spins? [no], types [ext4]
[2017-03-15T06:23:07,413][INFO ][o.e.e.NodeEnvironment    ] [BrYURuf] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-03-15T06:23:07,414][INFO ][o.e.n.Node               ] node name [BrYURuf] derived from node ID [BrYURuf8TqCFeiAfgpLhVg]; set [node.name] to override
[2017-03-15T06:23:07,416][INFO ][o.e.n.Node               ] version[5.2.2], pid[3810], build[f9d9b74/2017-02-24T17:26:45.835Z], OS[Linux/4.4.51-40.58.amzn1.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-03-15T06:23:08,235][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [aggs-matrix-stats]
[2017-03-15T06:23:08,236][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [ingest-common]
[2017-03-15T06:23:08,236][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [lang-expression]
[2017-03-15T06:23:08,237][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [lang-groovy]
[2017-03-15T06:23:08,237][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [lang-mustache]
[2017-03-15T06:23:08,237][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [lang-painless]
[2017-03-15T06:23:08,237][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [percolator]
[2017-03-15T06:23:08,238][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [reindex]
[2017-03-15T06:23:08,238][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [transport-netty3]
[2017-03-15T06:23:08,238][INFO ][o.e.p.PluginsService     ] [BrYURuf] loaded module [transport-netty4]
[2017-03-15T06:23:08,239][INFO ][o.e.p.PluginsService     ] [BrYURuf] no plugins loaded
[2017-03-15T06:23:10,093][INFO ][o.e.n.Node               ] initialized
[2017-03-15T06:23:10,094][INFO ][o.e.n.Node               ] [BrYURuf] starting ...
[2017-03-15T06:23:10,214][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 84:11:40:8a:08:7e:f7:97
[2017-03-15T06:23:10,280][INFO ][o.e.t.TransportService   ] [BrYURuf] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2017-03-15T06:23:10,286][WARN ][o.e.b.BootstrapChecks    ] [BrYURuf] max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
[2017-03-15T06:23:10,286][WARN ][o.e.b.BootstrapChecks    ] [BrYURuf] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-03-15T06:23:13,381][INFO ][o.e.c.s.ClusterService   ] [BrYURuf] new_master {BrYURuf}{BrYURuf8TqCFeiAfgpLhVg}{wnSTAlCrS4aBEv5mney7Lg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-03-15T06:23:13,461][INFO ][o.e.g.GatewayService     ] [BrYURuf] recovered [0] indices into cluster_state
[2017-03-15T06:23:13,463][INFO ][o.e.h.HttpServer         ] [BrYURuf] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2017-03-15T06:23:13,463][INFO ][o.e.n.Node               ] [BrYURuf] started
```

```bash
### ｷﾀ━━━━｡ﾟ+.ヽ(´∀`*)ﾉ ﾟ+.ﾟ━━━━!!
$ curl http://localhost:9200/
{
  "name" : "BrYURuf",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ZFai-NKEQy200ZLjp4MFEw",
  "version" : {
    "number" : "5.2.2",
    "build_hash" : "f9d9b74",
    "build_date" : "2017-02-24T17:26:45.835Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by MofuMofu2** [comment]
AmazonLinuxでのインストール手順とかはVer2とかの拡張で追記したいですが、Java8が必要なことは明記した方が良いと思いました。本文に追記しています。

**Comment by MofuMofu2** [comment]
これ、Amazon LinuxにESをインストールする前にAWS側でセキュリティポリシーは設定しましたか？    
事前にhttp通信できるように設定してるのか気になりましたー。
